"""Guard: every script under `tools/` must be named by at least one test file.

This is the test that would have made `build_catalog.py`'s silent breakage
(`TypeError: build() missing 1 required positional argument: 'identity'`)
impossible to ship uncovered for as long as it was: it fails loudly, at test
time, the moment a new script lands in `tools/` without any test file that
mentions its name -- rather than relying on someone remembering to add one.

Any legitimate exclusion belongs in `NOT_A_COVERED_SCRIPT` below, with a
comment explaining why it is exempt. Nothing is ever skipped silently.
"""
from __future__ import annotations

import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOOLS_DIR = ROOT / "tools"
TESTS_DIR = ROOT / "tests"

NOT_A_COVERED_SCRIPT = {
    # Bytecode cache, not a script; regenerated by the interpreter and never
    # itself a thing that could carry an untested behavior change.
    "__pycache__",
}


class ToolsHaveTestCoverageTest(unittest.TestCase):
    def test_every_tool_is_named_by_at_least_one_test_file(self):
        test_sources = "\n".join(
            path.read_text(encoding="utf-8") for path in sorted(TESTS_DIR.glob("test_*.py"))
        )
        uncovered = []
        for entry in sorted(TOOLS_DIR.iterdir()):
            if entry.name in NOT_A_COVERED_SCRIPT:
                continue
            if entry.is_dir():
                # A directory under tools/ that isn't the exempted cache is
                # unexpected shape for this guard; fail loudly rather than
                # silently walking into it or skipping it.
                self.fail(
                    f"tools/{entry.name} is a directory this guard does not know how to "
                    "check for coverage -- add it to NOT_A_COVERED_SCRIPT with a reason, "
                    "or extend this test to look inside it."
                )
            # `entry.stem` handles both `build_catalog.py` (stem `build_catalog`)
            # and the extensionless `pegasus-skill-registry` (stem is itself).
            if entry.stem not in test_sources:
                uncovered.append(entry.name)
        self.assertEqual(
            uncovered, [],
            f"tools/ scripts with no referencing test file: {uncovered} -- "
            "add a tests/test_<name>.py that runs it, or document an explicit "
            "exclusion in NOT_A_COVERED_SCRIPT with a reason.",
        )


if __name__ == "__main__":
    unittest.main()
